# The configuration basically follows Butter Knife's one.
# https://github.com/JakeWharton/butterknife/blob/master/.travis.yml
# https://docs.travis-ci.com/user/languages/android/
language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=10 # minutes
  matrix:
    - TARGET=unit
    - TARGET=instrumentation

install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools

script: ./build.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
