# The configuration basically follows Butter Knife's one.
# https://github.com/JakeWharton/butterknife/blob/master/.travis.yml
# https://docs.travis-ci.com/user/languages/android/
language: android

env:
  global:
    - TARGET=unit

script: travis_wait ./build.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
